# Deployment of a standalone Blazor WebAssembly application to GitHub Pages
name: GitHubPagesDeploy

# Define a environment variable to indicate the publish location from the Blazor WebAssembly app
env:
  PUBLISH_DIR: Client/bin/Release/net5.0/publish/wwwroot

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      # Extract repository name
      # github.repository is in format "/erwinkn/hnpwa-blazor" and we want to extract "hnpwa-blazor"
      - name: Extract repository name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | awk -F'/' '{print $2}')" >> $GITHUB_ENV

      # Rewrite base url with name of the repository
      - name: Change base URL in wwwroot/index.html
        run: sed -i -e "s/<base href=\".*\"/<base href=\"\/$REPO_NAME\/\"/" wwwroot/index.html 

      # Install Node packages
      - name: Install Node packages
        run: npm install

      # Build and publish Blazor WebAssembly
      - name: Publish app
        run: dotnet publish -c Release
        
      # GitHub Action to deploy static files to GitHub Pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ env.PUBLISH_DIR }}
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
          # Uncomment the following line if you have a custom domain name
          # cname: demo.erwinkuhn.com
